# Generated by Django 4.2.27 on 2025-12-12 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tarefassamc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_interessado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('CPF', models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF')),
                ('tarefa_n', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tarefas')),
                ('tarefa_a', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tarefas anterior')),
                ('sei_n', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número SEI')),
                ('procj', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Processo')),
                ('servico', models.CharField(choices=[('ANALISE', 'ANALISE'), ('ANALISE cobranca', 'ANALISE - Cobrança'), ('ANALISE exigencia', 'ANALISE - Exigência'), ('ANALISE corregedoria', 'ANALISE - Corregedoria'), ('ANALISE pendencia', 'ANALISE - Pendência'), ('ANALISE Concluir', 'ANALISE - Concluir'), ('ANALISE recurso', 'ANALISE - Recurso'), ('ANALISE judicial', 'ANALISE - Judicial'), ('CONCLUIDO', 'CONCLUIDO'), ('CONCLUIDO pendente', 'CONCLUIDO - pendente'), ('PA', 'PA - Aguardando Processo'), ('PARECER SOCIAL', 'PARECER SOCIAL - Aguardando Parecer Social'), ('PERICIA', 'PERICIA - Aguardando Perícia Médica'), ('PROCURADORIA', 'PROCURADORIA - Aguardando Procuradoria')], max_length=100, null=True, verbose_name='Serviço')),
                ('nome_serv', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Serviço')),
                ('der_tarefa', models.CharField(blank=True, max_length=20, null=True, verbose_name='DER Tarefa')),
                ('data_ci', models.CharField(blank=True, max_length=20, null=True, verbose_name='Data da ciência')),
                ('nb1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Benefício 1')),
                ('nb2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Benefício 2')),
                ('sit_ben', models.CharField(blank=True, max_length=100, null=True, verbose_name='Situação do Benefício')),
                ('aps', models.CharField(blank=True, max_length=100, null=True, verbose_name='APS Manutenção')),
                ('prazo', models.CharField(blank=True, choices=[('30 dias', '30 dias'), ('60 dias', '60 dias')], max_length=100, null=True, verbose_name='Prazo Defesa')),
                ('defesa_ap', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=100, null=True, verbose_name='Apresentou defesa?')),
                ('categoria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoria da irregularidade')),
                ('tip_con', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Conclusão')),
                ('oficio1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ofício Defesa')),
                ('oficio2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ofício Recurso')),
                ('AR', models.TextField(blank=True, null=True, verbose_name='Aviso de Recebimento e documentos')),
                ('Competencia', models.DateField(blank=True, null=True, verbose_name='Competência')),
                ('data_irregular', models.DateField(blank=True, null=True, verbose_name='Data de início da irregularidade')),
                ('Periodo_irregular', models.TextField(blank=True, null=True, verbose_name='Periodo irregular')),
                ('valor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Valor do débito')),
                ('obs1', models.TextField(blank=True, null=True, verbose_name='Fatos')),
                ('obs2', models.TextField(blank=True, null=True, verbose_name='Direito e conclusão')),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsável Legal')),
                ('CPF_R', models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF Responsável')),
                ('Conclusao', models.CharField(blank=True, choices=[('REGULAR', 'REGULAR'), ('IRREGULAR boa fe', 'IRREGULAR - Boa fé'), ('IRREGULAR ma fe', 'IRREGULAR - Má fé'), ('PARCIALMENTE IRREGULAR', 'PARCIALMENTE IRREGULAR')], max_length=100, null=True, verbose_name='Conclusão')),
                ('status', models.TextField(blank=True, null=True, verbose_name='Status')),
                ('historico', models.TextField(blank=True, null=True, verbose_name='Histórico')),
                ('servidor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Matrícula Responsável')),
                ('nome_tarefa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tarefas.tipo_servico', verbose_name='Tipo de Tarefa')),
            ],
        ),
    ]
