# Generated by Django 4.2.27 on 2025-12-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_tarefassamc_assigned_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefassamc',
            name='procj',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Processo Judicial'),
        ),
        migrations.AlterField(
            model_name='tarefassamc',
            name='status',
            field=models.TextField(blank=True, choices=[('PENDENTE', 'PENDENTE'), ('CONCLUIDA_INTERMEDIARIA', 'CONCLUÍDA - INTERMEDIÁRIA'), ('CONCLUIDA_FINALIZADA', 'CONCLUÍDA - FINALIZADA')], max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='tarefassamc',
            name='tarefa_a',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tarefa Anterior'),
        ),
        migrations.AlterField(
            model_name='tarefassamc',
            name='tarefa_n',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tarefa Principal'),
        ),
    ]
