# Generated by Django 4.2.27 on 2025-12-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_alter_tarefassamc_procj_alter_tarefassamc_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefassamc',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDENTE', 'Pendente'), ('EM ANALISE', 'Em Análise'), ('CONCLUIDO', 'Concluído'), ('CONCLUIDO PENDENTE', 'Concluído Pendente'), ('AGUARDANDO PROCESSO', 'Aguardando Processo'), ('AGUARDANDO PARECER', 'Aguardando Parecer'), ('AGUARDANDO PERICIA', 'Aguardando Perícia'), ('AGUARDANDO PROCURADORIA', 'Aguardando Procuradoria')], max_length=100, null=True, verbose_name='Status'),
        ),
    ]
