# Generated by Django 4.2.27 on 2025-12-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0005_alter_tarefassamc_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefassamc',
            old_name='AR',
            new_name='AR1',
        ),
        migrations.AddField(
            model_name='tarefassamc',
            name='AR2',
            field=models.TextField(blank=True, null=True, verbose_name='Aviso de Recebimento e documentos'),
        ),
        migrations.AlterField(
            model_name='tarefassamc',
            name='oficio1',
            field=models.DateField(blank=True, max_length=20, null=True, verbose_name='Ofício Defesa'),
        ),
        migrations.AlterField(
            model_name='tarefassamc',
            name='oficio2',
            field=models.DateField(blank=True, max_length=20, null=True, verbose_name='Ofício Recurso'),
        ),
        migrations.AlterField(
            model_name='tarefassamc',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDENTE', 'PENDENTE'), ('PENDENTE', 'PENDENTE - CORREÇÃO'), ('CONCLUIDA_INTERMEDIARIA', 'CONCLUÍDA - INTERMEDIÁRIA'), ('CONCLUIDA_FINALIZADA', 'CONCLUÍDA - FINALIZADA')], max_length=100, null=True, verbose_name='Status'),
        ),
    ]
