# Generated by Django 4.2.27 on 2025-12-22 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0006_rename_ar_tarefassamc_ar1_tarefassamc_ar2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefassamc',
            name='env_serv',
            field=models.CharField(blank=True, choices=[('Servidor Ativo', 'Servidor Ativo'), ('Servidor Inativo - demitido/aposentado', 'Servidor Inativo - demitido/aposentado'), ('Pensionista', 'Pensionista'), ('Não Envolvido', 'Não Envolvido')], max_length=50, null=True, verbose_name='Envolvimento de Servidor? Informe Situação Atual'),
        ),
        migrations.AddField(
            model_name='tarefassamc',
            name='resp_credito',
            field=models.CharField(blank=True, choices=[('1', 'Titular do benefício'), ('2', 'Responsável Legal')], max_length=100, null=True, verbose_name='Quem é o responsável pelo crédito?'),
        ),
        migrations.AlterField(
            model_name='tarefassamc',
            name='nome_tarefa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tarefas.tipo_servico', verbose_name='Fase da Análise'),
        ),
        migrations.AlterField(
            model_name='tarefassamc',
            name='tip_con',
            field=models.CharField(blank=True, choices=[('Crédito', 'Crédito'), ('Dano ao Erário', 'Dano ao Erário')], max_length=100, null=True, verbose_name='Tipo de Crédito Devido'),
        ),
    ]
