# Generated by Django 4.2.27 on 2025-12-22 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0007_tarefassamc_env_serv_tarefassamc_resp_credito_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='nome_motiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='tarefassamc',
            name='servidor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Matrícula Servidor Responsável'),
        ),
        migrations.AlterField(
            model_name='tarefassamc',
            name='nome_serv',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='tarefas.nome_motiv', verbose_name='Motivo do Ressarcimento'),
        ),
    ]
