# Generated by Django 4.2.27 on 2025-12-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0008_nome_motiv_alter_tarefassamc_servidor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefassamc',
            name='AR1',
            field=models.CharField(blank=True, choices=[('AR Digital', 'AR Digital'), ('Edital', 'Edital'), ('Atestado Pessoal', 'Atestado Pessoal'), ('Acesso à tarefa eletrônica de cobrança administrativa', 'Acesso à tarefa eletrônica de cobrança administrativa')], max_length=100, null=True, verbose_name='Aviso de Recebimento e documentos - Qual o tipo do comprovante?'),
        ),
        migrations.AlterField(
            model_name='tarefassamc',
            name='AR2',
            field=models.TextField(blank=True, choices=[('AR Digital', 'AR Digital'), ('Edital', 'Edital'), ('Atestado Pessoal', 'Atestado Pessoal'), ('Acesso à tarefa eletrônica de cobrança administrativa', 'Acesso à tarefa eletrônica de cobrança administrativa')], null=True, verbose_name='Aviso de Recebimento e documentos - Qual o tipo do comprovante?'),
        ),
        migrations.AlterField(
            model_name='tarefassamc',
            name='oficio1',
            field=models.DateField(blank=True, max_length=20, null=True, verbose_name='Ofício Defesa - ciência'),
        ),
        migrations.AlterField(
            model_name='tarefassamc',
            name='oficio2',
            field=models.DateField(blank=True, max_length=20, null=True, verbose_name='Ofício Recurso - ciência'),
        ),
    ]
