# Generated by Django 4.2.27 on 2025-12-23 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0009_alter_tarefassamc_ar1_alter_tarefassamc_ar2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='conc_analise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conc', models.CharField(max_length=100)),
                ('conc_exp', models.TextField(blank=True, null=True)),
                ('fim', models.CharField(blank=True, choices=[('PROCEDENTE', 'PROCEDENTE'), ('PARCIALMENTE PROCEDENTE', 'PARCIALMENTE PROCEDENTE'), ('IMPROCEDENTE', 'IMPROCEDENTE')], max_length=100, null=True, verbose_name='')),
            ],
        ),
        migrations.AlterField(
            model_name='tarefassamc',
            name='Conclusao',
            field=models.CharField(blank=True, choices=[('REGULAR', 'REGULAR'), ('IRREGULAR Boa fé', 'IRREGULAR - Boa fé'), ('IRREGULAR Má fé', 'IRREGULAR - Má fé'), ('PARCIALMENTE IRREGULAR', 'PARCIALMENTE IRREGULAR')], max_length=100, null=True, verbose_name='Conclusão'),
        ),
        migrations.AlterField(
            model_name='tarefassamc',
            name='obs1',
            field=models.TextField(blank=True, null=True, verbose_name='Relatório - faça um breve resumo da defesa:'),
        ),
        migrations.AddField(
            model_name='tarefassamc',
            name='es_conc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tarefas.conc_analise', verbose_name='Conclusão da Análise'),
        ),
    ]
