# Generated by Django 4.2.27 on 2025-12-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0010_conc_analise_alter_tarefassamc_conclusao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefassamc',
            name='data_ci',
        ),
        migrations.AddField(
            model_name='tarefassamc',
            name='data_def',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Data da ciência - ofício defesa'),
        ),
        migrations.AddField(
            model_name='tarefassamc',
            name='data_rec',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Data da ciência - ofício recurso'),
        ),
        migrations.AlterField(
            model_name='tarefassamc',
            name='obs2',
            field=models.TextField(blank=True, null=True, verbose_name='Direito e conclusão - vai aparecer antes da conclusão'),
        ),
    ]
