# Generated by Django 4.2.27 on 2026-01-08 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tarefas', '0011_remove_tarefassamc_data_ci_tarefassamc_data_def_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GRU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiario_nome', models.CharField(blank=True, max_length=200, null=True)),
                ('beneficiario_cpf', models.CharField(blank=True, max_length=30, null=True)),
                ('codigo_recolhimento', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('competencia', models.DateField(blank=True, null=True)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('PAGA', 'PAGA'), ('VENCIDA', 'VENCIDA'), ('CANCELADA', 'CANCELADA')], default='PENDENTE', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='gru_pdfs/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grus_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GRU',
                'verbose_name_plural': 'GRUs',
            },
        ),
    ]
