# Generated by Django 4.2.7 on 2026-01-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0012_gru'),
    ]

    operations = [
        migrations.AddField(
            model_name='gru',
            name='concluida_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarefassamc',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tarefassamc',
            name='concluida_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
