# Generated by Django 4.2.7 on 2026-01-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0013_gru_concluida_em_tarefassamc_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefassamc',
            name='concluida_em',
            field=models.DateField(blank=True, null=True),
        ),
    ]
