# Generated by Django 4.2.7 on 2026-03-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0015_integracao_calculadora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefassamc',
            name='historico',
            field=models.TextField(blank=True, null=True, verbose_name='Histórico(Fundamento da cobrança)'),
        ),
    ]
