
# Generated by Django 4.2.7 on 2026-03-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0017_adicionar_campo_calculos_aprovados'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefassamc',
            name='calculos_aprovados',
            field=models.BooleanField(default=False, verbose_name='Cálculos Aprovados (migrar para Valor)'),
        ),
    ]
